apiVersion: v1
kind: Pod

metadata:
  name: productservicepod
  labels:
    app: productservice
    

spec:
  containers:
   - name: productservicecontainer
     image: sivavalluru/productservice
#     envFrom:
#      - configMapRef:
#          name: productservicecm
#      - secretRef:
#          name: mysql-secret      
#     env:      
#      - name: spring.profiles.active
#        value: mysql
     
# kubectl create configmap mysqlcm  --from-literal=MYSQL_ROOT_PASSWORD=root --from-literal=MYSQL_DATABASE=sivatrainingdb --dry-run=client -o yaml     
---

apiVersion: v1
kind: Pod

metadata:
  name: mysqlpod
  labels:
    app: mysql
    

spec:
  containers:
   - name: mysql
     image: mysql
#     envFrom:
#      - configMapRef:
#          name: mysqlcm
      
     env:      
      - name: MYSQL_ROOT_PASSWORD
        value: root
      - name: MYSQL_DATABASE
        value: sivatrainingdb