server:
  port: 8081
  
eureka:
  instance:
    hostname: ${eurekahostname:localhost}
    instance-id: ${spring.application.name}:${random.value} 
  client:
    service-url:
      defaultZone: http://${eureka.instance.hostname}:5001/eureka

spring:
  application:
    name: booking-service
 # datasource:
  #  url: jdbc:mysql://localhost/cargotracker
  #  username: root
  #  password: root

  cloud:
    stream:
      bindings:
        cargoBookingChannel:
          destination: cargoBookings          
          binder: rabbit
        cargoRoutingChannel:
          destination: cargoRoutings         
          binder: rabbit
        cargoHandlingChannel:
          destination: cargoHandling
          group: cargoHandlingInBookingQueue
          binder: rabbit
      binders:
        rabbit:
          type: rabbit
          environment:
            spring:
              rabbitmq:
                host: ${rabbithostname:localhost}
                port: 5672
                username: guest
                password: guest
  jpa:
    generate-ddl: true
  h2:
    console:
      settings:
        web-allow-others: true
      enabled: true
      path: /h2-console
      
  datasource:
    url:  jdbc:h2:mem:mydb
    username: siva
    password: siva
      