apiVersion: v1
kind: ReplicationController
metadata:
  name: productservice-rc
spec:
  replicas: 3
  selector:
    app: productservice
  template:
    metadata:
      name: productservicepod
      labels:
        app: productservice
    spec:
      containers:
      - name: productservicecontainer
        image: sivavalluru/productservice
       